# PowerShell Folder Cleanup Script Template
# Replace [TARGET] with your root folder path
# Generated by: folder-cleanup skill
# Safe to re-run (idempotent). Review before executing.

$ErrorActionPreference = "Stop"
$root = "[TARGET]"  # e.g. "~/dev/"

$summary = @{ MOVED = 0; DELETED = 0; CREATED = 0; SKIPPED = 0; WARNINGS = 0 }

Write-Host "Starting cleanup of $root..." -ForegroundColor Cyan
Write-Host "------------------------------------"

function Safe-Move {
    param([string]$Src, [string]$Dest)
    if (Test-Path $Src) {
        $parent = Split-Path -Path $Dest -Parent
        if (-not (Test-Path $parent)) { New-Item -ItemType Directory -Path $parent -Force | Out-Null }
        Move-Item -Path $Src -Destination $Dest -Force
        Write-Host "  MOVED   : $Src -> $Dest"
        $script:summary.MOVED++
    } else {
        Write-Host "  SKIPPED : Not found: $Src"
        $script:summary.SKIPPED++
    }
}

function Safe-Remove-Dir {
    param([string]$Path)
    if (Test-Path $Path) {
        if ((Get-ChildItem -Path $Path -Force).Count -eq 0) {
            Remove-Item -Path $Path -Force
            Write-Host "  DELETED : $Path"
            $script:summary.DELETED++
        } else {
            Write-Host "  WARNING : Not empty, skipping: $Path" -ForegroundColor Yellow
            $script:summary.SKIPPED++
            $script:summary.WARNINGS++
        }
    } else {
        Write-Host "  SKIPPED : Not found: $Path"
        $script:summary.SKIPPED++
    }
}

function Safe-Remove-File {
    param([string]$Path)
    if (Test-Path $Path) {
        Remove-Item -Path $Path -Force
        Write-Host "  DELETED : $Path"
        $script:summary.DELETED++
    } else {
        Write-Host "  SKIPPED : Not found: $Path"
        $script:summary.SKIPPED++
    }
}

function Create-Doc {
    param([string]$Path, [string]$Content)
    try {
        Set-Content -Path $Path -Value $Content.Trim() -Encoding UTF8 -Force
        Write-Host "  CREATED : $Path"
        $script:summary.CREATED++
    } catch {
        Write-Host "  ERROR   : $Path - $($_.Exception.Message)" -ForegroundColor Red
        $script:summary.WARNINGS++
    }
}

# =============================================================================
# PHASE 2: FILE MOVES
# =============================================================================
Write-Host "`n[Phase 2] Moving files..."

# Add moves here:
# Safe-Move "$root\source-folder" "$root\dest-folder"


# =============================================================================
# PHASE 3: DELETE EMPTY FOLDERS AND FILES
# NOTE: Always remove leaf dirs first, then parents
# =============================================================================
Write-Host "`n[Phase 3] Removing empty folders and stray files..."

# Add deletes here (deepest first):
# Safe-Remove-Dir "$root\parent\child"
# Safe-Remove-Dir "$root\parent"
# Safe-Remove-File "$root\stray-file.ext"


# =============================================================================
# PHASE 4: CREATE HOUSEKEEPING DOCS
# =============================================================================
Write-Host "`n[Phase 4] Creating housekeeping docs..."

# Add doc creation here:
# Create-Doc "$root\FOLDER-RULES.md" @"
# [content]
# "@


# =============================================================================
# SUMMARY
# =============================================================================
Write-Host "`n------------------------------------" -ForegroundColor Cyan
Write-Host "Cleanup Complete" -ForegroundColor Cyan
Write-Host "------------------------------------"
Write-Host ("  MOVED   : {0}" -f $summary.MOVED)
Write-Host ("  DELETED : {0}" -f $summary.DELETED)
Write-Host ("  CREATED : {0}" -f $summary.CREATED)
Write-Host ("  SKIPPED : {0}" -f $summary.SKIPPED)
Write-Host "------------------------------------"
if ($summary.WARNINGS -gt 0) {
    Write-Host ("  {0} warning(s) - review output above" -f $summary.WARNINGS) -ForegroundColor Yellow
} else {
    Write-Host "  No warnings. All clean." -ForegroundColor Green
}
